name: Build and Push to GHCR

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/boreddaoist/boringcomfy:latest
            ghcr.io/boreddaoist/boringcomfy:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/boreddaoist/BoringComfy
          build-args: |
            CIVITAI_TOKEN=${{ secrets.CIVITAI_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max